name: Selenium Tests

on: [push]

env:
  SELENIUM_DRIVER_VERSION: "109.0.5414.120"

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Install dependencies
          run: |
          chmod +x ./gradlew
          ls -ltr
          ./gradlew clean build --no-daemon

      - name: Download ChromeDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/${SELENIUM_DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          rm chromedriver_linux64.zip

      - name: Set ChromeDriver path
        run: export PATH=$PATH:$PWD

      - name: Run Selenium Tests
          run: ./gradlew test -Dwebdriver.chrome.driver=./chromedriver --no-daemon